name: Generate snake game animation

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate snake game animation
        run: snk generate --filename snake.svg

      - name: Upload snake game animation
        uses: actions/upload-artifact@v3
        with:
          name: snake.svg
          path: snake.svg
